pr:
  branches:
    include:
    - develop
    - release/*
    - hotfix/*
    - master
    
trigger:
- develop
- release/*
- hotfix/*
- master

pool:
  vmImage: windows-latest

variables:
    chromeDriverVersion: 113.0.5672.63
    revisionNumber: $[counter('revisions', 35)]
    isPullRequest: $[eq(variables['Build.Reason'], 'PullRequest')]

steps:
- task: PowerShell@2
  displayName: 'Download ChromeDriver'
  inputs:
    filePath: '$(Build.SourcesDirectory)\Husa.Uploader\Scripts\DownloadChromeDriver.ps1'
    arguments: '-version "$(chromeDriverVersion)" -path "$(Build.SourcesDirectory)\Husa.Uploader\Husa.Uploader.Desktop"'

- task: PowerShell@2
  displayName: 'Update HTML with Version'
  inputs:
    filePath: '$(Build.SourcesDirectory)\Husa.Uploader\Scripts\UpdatePublishAppVersion.ps1'
    arguments: '-revision "$(revisionNumber)" -csprojPath "$(Build.SourcesDirectory)\Husa.Uploader\Husa.Uploader.Desktop\Husa.Uploader.Desktop.csproj" -htmlFilePath "$(Build.SourcesDirectory)\Husa.Uploader\Husa.Uploader.Desktop\Deployment\Publish.html" -destinationFilePath "$(build.artifactstagingdirectory)"'

- task: DotNetCoreCLI@2 
  displayName: 'dotnet restore'
  inputs:
    command: restore
    projects: '**/Husa.Uploader/Husa.Uploader.sln'
    restoreArguments: '/property:Configuration=Release'
    feedsToUse: 'select'
    vstsFeed: 'f820f957-6781-4cd6-b5f5-e720c189507f/891ce0ed-37b7-4336-b1fe-079c0525a171'

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    projects: '**/Husa.Uploader/Husa.Uploader.sln'
    arguments: '--configuration Release --no-restore'

- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  continueOnError: false
  inputs:
    command: test
    projects: '**/Husa.Uploader/Husa.Uploader.sln'
    arguments: '--configuration Release --no-build --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=cobertura --logger trx'
    publishTestResults: true

- task: MSBuild@1
  displayName: 'publish with ClickOnce'
  condition: ne(variables.isPullRequest, true)
  inputs:
    solution: '**/Husa.Uploader.Desktop/Husa.Uploader.Desktop.csproj'
    msbuildArguments: '/target:Publish /p:ApplicationRevision=$(revisionNumber) /p:GenerateManifests=true /p:UseApplicationTrust=true /p:Install=true /p:InstallFrom=Web /p:MapFileExtensions=true /p:IsWebBootstrapper=true /p:CreateWebPageOnPublish=true /p:WebPageFileName=Publish.html /P:PublishProfile=$(Build.SourcesDirectory)\Husa.Uploader\Husa.Uploader.Desktop\Properties\PublishProfiles\ClickOnceProfile.pubxml'
    platform: 'AnyCPU'
    configuration: 'Release'
    logFileVerbosity: 'detailed'

- task: PublishBuildArtifacts@1
  displayName: 'publish Artifact: drop'
  condition: ne(variables.isPullRequest, true)
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
