using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Husa.Core.UploaderBase
{
    public class ResidentialLeaseRequest
    {
        // Never remove this property
        public string WorkingBy { get; set; }
        
        public short? SysStatusID { get; set; }
        public string SysState { get; set; }
        public int? SysCreatedBy { get; set; }
        public DateTime? SysCreatedOn { get; set; }
        public int? SysModifiedBy { get; set; }
        public DateTime? SysModifiedOn { get; set; }
        public int? SysOwnedBy { get; set; }
        public int? ResidentialLeaseID { get; set; }
        public int? MarketID { get; set; }
        public int? CommunityProfileID { get; set; }
        public int? PlanProfileID { get; set; }
        public int? AgentID_SELL { get; set; }
        public int? UserID_SubmittedBy { get; set; }
        public int? NumDiningAreas { get; set; }
        public string LotNum { get; set; }
        public DateTime? ListDate { get; set; }
        public string AppFee { get; set; }
        public int? BathsHalf { get; set; }
        public DateTime? ContractDate { get; set; }
        public string LotSizeAcres { get; set; }
        public int? OtherRoom2Length { get; set; }
        public string NonRefunPetFee { get; set; }
        public string Bed2Level { get; set; }
        public int? GarageCapacity { get; set; }
        public string Restrictions { get; set; }
        public int? UtilityRoomWidth { get; set; }
        public string WDConnections { get; set; }
        public int? LivingRoom3Width { get; set; }
        public int? NumLivingAreas { get; set; }
        public string PetPolicy { get; set; }
        public string HousingStyleDesc { get; set; }
        public int? BathsFull { get; set; }
        public string InteriorDesc { get; set; }
        public string StreetNumDisplay { get; set; }
        public string Bed1Level { get; set; }
        public int? BathsFullLevel3 { get; set; }
        public int? StudyWidth { get; set; }
        public string NumberFireplaces { get; set; }
        public string SecurityDesc { get; set; }
        public string AssocPhone { get; set; }
        public string Date { get; set; }
        public string UtilitiesDesc { get; set; }
        public string IsWaterFront { get; set; }
        public int? BathsFullLevel1 { get; set; }
        public string UtilityRoomLevel { get; set; }
        public string AgentListApptPhone { get; set; }
        public string City { get; set; }
        public string SchoolName7 { get; set; }
        public string isFutureUse { get; set; }
        public string HasHandicapAmenities { get; set; }
        public string SchoolDistrict { get; set; }
        public int? Bed2Width { get; set; }
        public int? Bed1Length { get; set; }
        public string Bed4Level { get; set; }
        public string ExteriorDesc { get; set; }
        public string SchoolName2 { get; set; }
        public int? DiningRoomLength { get; set; }
        public DateTime? estimatedFutureDate { get; set; }
        public DateTime? MoveInDate { get; set; }
        public int? BathsHalfLevel3 { get; set; }
        public string MUDDistrict { get; set; }
        public int? BreakfastLength { get; set; }
        public string MLSSubArea { get; set; }
        public string ApplicationFeePay { get; set; }
        public int? Bed5Width { get; set; }
        public int? Bed4Width { get; set; }
        public string LivingRoom2Level { get; set; }
        public string KitchenEquipmentDesc { get; set; }
        public string Bed3Level { get; set; }
        public string WillSubdivide { get; set; }
        public string PropSubType { get; set; }
        public string NumStories { get; set; }
        public string AgentPrivateRemarks { get; set; }
        public string OwnerName { get; set; }
        public string LotDim { get; set; }
        public string NumberGuestAllowed { get; set; }
        public string LeaseTerms { get; set; }
        public string Legal { get; set; }
        public string Occupancy { get; set; }
        public string UnitNum { get; set; }
        public string County { get; set; }
        public string AgentSell { get; set; }
        public string HOA { get; set; }
        public string LivingRoom3Level { get; set; }
        public int? BathsHalfLevel2 { get; set; }
        public string EnergyDesc { get; set; }
        public int? BathsHalfLevel1 { get; set; }
        public string AgentList { get; set; }
        public string NumberOfVehicles { get; set; }
        public string OwnerOtherPhone { get; set; }
        public string CompBuy { get; set; }
        public string LotDesc { get; set; }
        public string HasSecuritySys { get; set; }
        public string DiningRoomLevel { get; set; }
        public int? Bed5Length { get; set; }
        public string GreenFeatures { get; set; }
        public string AppFeeAmount { get; set; }
        public bool? SellingAgentPresent { get; set; }
        public string OwnerPhone { get; set; }
        public int? GarageLength { get; set; }
        public string BuilderName { get; set; }
        public string StudyLevel { get; set; }
        public decimal ListPrice { get; set; }
        public int? KitchenLength { get; set; }
        public string OtherRoom1Level { get; set; }
        public string SqFtSource { get; set; }
        public string HasPool { get; set; }
        public string NumberOfPetsAllowed { get; set; }
        public string SMARTFEATURESAPP { get; set; }
        public string FenceDesc { get; set; }
        public string BreakfastLevel { get; set; }
        public int? Bed4Length { get; set; }
        public string LaundryLocDesc { get; set; }
        public string HandicapDesc { get; set; }
        public DateTime? ExpiredDate { get; set; }
        public string CommonFeatures { get; set; }
        public int? PhotoCount { get; set; }
        public string BedBathDesc { get; set; }
        public string DepositPet { get; set; }
        public string PublicRemarks { get; set; }
        public string MLSNum { get; set; }
        public int? DiningRoomWidth { get; set; }
        public int? SqFtTotal { get; set; }
        public DateTime? ResourcesUpdatedOn { get; set; }
        public DateTime? BuildCompletionDate { get; set; }
        public DateTime? LeasedDate { get; set; }
        public string StreetDir { get; set; }
        public string NumLakes { get; set; }
        public string CityCode { get; set; }
        public string MLSArea { get; set; }
        public int? KitchenWidth { get; set; }
        public string ParkingDesc { get; set; }
        public DateTime? OffMarketDate { get; set; }
        public int? Bed3Width { get; set; }
        public string ShowingInstructions { get; set; }
        public decimal LeasedPrice { get; set; }
        public DateTime? Modified { get; set; }
        public int? Bed3Length { get; set; }
        public DateTime? SysCompletedOn { get; set; }
        public int? BreakfastWidth { get; set; }
        public string OtherRoomDesc { get; set; }
        public string OtherRoom2Level { get; set; }
        public string Furnished { get; set; }
        public string Excludes { get; set; }
        public string IsMultiParcel { get; set; }
        public string Subdivision { get; set; }
        public string FloorLocationNumber { get; set; }
        public string KitchenLevel { get; set; }
        public string Acres { get; set; }
        public string GarageDesc { get; set; }
        public int? SysCompletedBy { get; set; }
        public string PoolDesc { get; set; }
        public int? OtherRoom1Length { get; set; }
        public string PlannedDevelopment { get; set; }
        public int? Beds { get; set; }
        public string HousingTypeDesc { get; set; }
        public string LotSize { get; set; }
        public int? OtherRoom2Width { get; set; }
        public string SchoolName1 { get; set; }
        public int? StudyLength { get; set; }
        public string LivingRoom1Level { get; set; }
        public string UtilityRoomDesc { get; set; }
        public string StreetName { get; set; }
        public int? OtherRoom1Width { get; set; }
        public string WaterfrontDesc { get; set; }
        public int? CarportCapacity { get; set; }
        public string AssocName { get; set; }
        public int? StreetNum { get; set; }
        public string DepositAmount { get; set; }
        public string SchoolName4 { get; set; }
        public int? Bed1Width { get; set; }
        public string LeaseConditions { get; set; }
        public string State { get; set; }
        public string TenantPays { get; set; }
        public string SchoolName5 { get; set; }
        public string SpecialNotes { get; set; }
        public string Directions { get; set; }
        public string CancelledReason { get; set; }
        public string Showing { get; set; }
        public short? ClassMarketID { get; set; }
        public DateTime? BackOnMarketDate { get; set; }
        public int? GarageWidth { get; set; }
        public int? LivingRoom1Length { get; set; }
        public int? LivingRoom3Length { get; set; }
        public string FloorsDesc { get; set; }
        public int? Bed2Length { get; set; }
        public string UID { get; set; }
        public string Zip { get; set; }
        public string MoniesRequired { get; set; }
        public string ListStatus { get; set; }
        public int? UtilityRoomLength { get; set; }
        public string FireplaceDesc { get; set; }
        public string GreenCerts { get; set; }
        public int? BathsHalfBasement { get; set; }
        public string LeaseType { get; set; }
        public string AssocFeeIncludes { get; set; }
        public string StreetType { get; set; }
        public int? YearBuilt { get; set; }
        public string MonthlyPetFee { get; set; }
        public string Bed5Level { get; set; }
        public int? BathsFullBasement { get; set; }
        public int AppliancesYN { get; set; }
        public string ConstructionDesc { get; set; }
        public int? NumFireplaces { get; set; }
        public int? LivingRoom2Length { get; set; }
        public string SchoolName3 { get; set; }
        public string SchoolName6 { get; set; }
        public int? LivingRoom2Width { get; set; }
        public string KitchenDesc { get; set; }
        public string CompensationPaid { get; set; }
        public string YearBuiltDesc { get; set; }
        public int? BathsFullLevel2 { get; set; }
        public string HeatSystemDesc { get; set; }
        public string Block { get; set; }
        public int? LivingRoom1Width { get; set; }
        public string CancelledOptionLease { get; set; }
        public string PropType { get; set; }
        public string OfficeList { get; set; }
        public int? DOM { get; set; }
        public int? CDOM { get; set; }
        public string individualOH { get; set; }
        public string AllowPendingList { get; set; }
        public string OHStartTimeSatOH { get; set; }
        public string OHEndTimeSat { get; set; }
        public string OHTypeSatOH { get; set; }
        public string OHRefreshmentsSatOH { get; set; }
        public string OHCommentsSat { get; set; }
        public string OHStartTimeSunOH { get; set; }
        public string OHEndTimeSunOH { get; set; }
        public string OHTypeSun { get; set; }
        public string OHRefreshmentsSun { get; set; }
        public string OHCommentsSunOH { get; set; }
        public string OHStartTimeMonOH { get; set; }
        public string OHEndTimeMon { get; set; }
        public string OHTypeMon { get; set; }
        public string OHRefreshmentsMon { get; set; }
        public string OHCommentsMonOH { get; set; }
        public string OHStartTimeTueOH { get; set; }
        public string OHEndTimeTueOH { get; set; }
        public string OHTypeTue { get; set; }
        public string OHRefreshmentsTue { get; set; }
        public string OHCommentsTueOH { get; set; }
        public string OHStartTimeWedOH { get; set; }
        public string OHEndTimeWed { get; set; }
        public string OHTypeWedOH { get; set; }
        public string OHRefreshmentsWedOH { get; set; }
        public string OHCommentsWed { get; set; }
        public string OHStartTimeThu { get; set; }
        public string OHEndTimeThu { get; set; }
        public string OHTypeThuOH { get; set; }
        public string OHRefreshmentsThuOH { get; set; }
        public string OHCommentsThu { get; set; }
        public string OHStartTimeFri { get; set; }
        public string OHEndTimeFri { get; set; }
        public string OHTypeFriOH { get; set; }
        public string OHRefreshmentsFriOH { get; set; }
        public string OHCommentsFri { get; set; }
        public string RealtorContactEmail { get; set; }
        public bool? FencedYard { get; set; }
        public string TypeFence { get; set; }
        public string CommissionLease { get; set; }
        public bool? AgentCommissionPercentYN { get; set; }
        public bool? AgentCommissionDollarsYN { get; set; }
    }
}
